import { useState } from 'react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { useScrollAnimation } from '@/hooks/use-scroll-animation';

const faqData = {
  "General & Capability": [
    {
      question: "What exactly is TOBE and how does it work?",
      answer: "TOBE is the world's first Generative Commerce platform by WNE3. It lets you create, customize, and order apparel or merchandise just by typing what you imagine — like \"a pastel hoodie with mountain art.\" Our AI instantly designs it, you preview it, and we make it only after you buy."
    },
    {
      question: "Can I really create anything, or are there design limits?",
      answer: "Almost anything — from simple text designs to full art styles, memes, or patterns. TOBE's AI interprets natural language, so even vague prompts like \"a hoodie that feels calm and minimal\" turn into tangible designs."
    },
    {
      question: "Do I need design experience to use TOBE?",
      answer: "Not at all. The platform is built for everyone. Whether you're a creator, student, or brand owner, you just describe what you want — no Photoshop, no templates."
    },
    {
      question: "Can I use TOBE for products beyond apparel?",
      answer: "Yes. While our first phase focuses on apparel and accessories, the ecosystem will soon expand to include home décor, stationery, gifts, and digital collectibles — all generated by your prompts."
    },
    {
      question: "Does TOBE also generate mockups and previews?",
      answer: "Yes, each design you create instantly appears on realistic product previews (like hoodies, mugs, or phone cases), so you can visualize before buying."
    },
    {
      question: "Do you offer a managed or creator-assist service?",
      answer: "Absolutely. For brands or creators who want hands-off management, the platform automatically creates and manages a personalized sub-store for you, handling everything from design to order fulfillment."
    }
  ],
  "Customization & Control": [
    {
      question: "How much control do I have over the final product design?",
      answer: "You have complete creative freedom — you can refine colors, text, placement, and style until it feels perfect. TOBE's AI remembers your preferences and evolves with every use."
    },
    {
      question: "Can I specify design style or theme?",
      answer: "Yes. You can ask for \"streetwear,\" \"minimalist,\" \"retro,\" \"eco aesthetic,\" or anything else — TOBE's AI adapts to your style and tone."
    },
    {
      question: "Can I generate collections or product lines under my brand?",
      answer: "Definitely. You can create cohesive collections, maintain your brand style, and even reuse previous prompts to generate complementary products."
    },
    {
      question: "Can I personalize products for gifts or events?",
      answer: "Yes — simply type, \"gift hoodie for best friend with our college name and inside joke,\" and TOBE will generate something one-of-a-kind."
    },
    {
      question: "Can small creators build their own stores?",
      answer: "Yes. Creators can open sub-stores inside TOBE, sell designs globally, and earn revenue. And while Amazon or Flipkart charge up to 25% commissions, TOBE keeps it under 2%, ensuring creators keep what they deserve."
    },
    {
      question: "Can I collaborate with other designers or creators?",
      answer: "Yes — you can co-create collections, share prompt templates, and launch limited drops together within the same ecosystem."
    }
  ],
  "Process & Workflow": [
    {
      question: "What's the step-by-step process for creating and ordering?",
      answer: "You describe your idea → AI generates designs → you preview and tweak → place order → product is manufactured on demand → shipped to your address."
    },
    {
      question: "How long does it take from creation to delivery?",
      answer: "Each item is made post-purchase. On average, it takes 3–5 days for domestic delivery."
    },
    {
      question: "Can I upload my own artwork or mix it with AI designs?",
      answer: "Yes, you can blend your uploaded files with AI-generated elements for a hybrid design approach."
    },
    {
      question: "How accurate are the final prints compared to the digital preview?",
      answer: "We use high-fidelity rendering and color calibration to ensure what you see is what you get — with <5% variation between mockup and final print."
    },
    {
      question: "Can I brand the packaging or add my logo?",
      answer: "Yes, premium and creator-tier users can include branded labels, packaging, and inserts."
    }
  ],
  "Pricing & Plans": [
    {
      question: "How does TOBE's pricing work?",
      answer: "TOBE has no upfront design fees. You only pay for what you order. Prices vary by product type and customization level."
    },
    {
      question: "Do you charge commissions or platform fees?",
      answer: "Only under 2% commission per sale for creators — far below Amazon or Etsy, which often charge 20–25%."
    },
    {
      question: "Is there a subscription model for creators or brands?",
      answer: "Yes — optional creator plans offer bulk credits, advanced analytics, branded storefronts, and early access to new AI tools."
    },
    {
      question: "Can I try TOBE for free?",
      answer: "Yes, every user gets a few free credits to explore AI product generation before purchasing."
    },
    {
      question: "Are there discounts for bulk or corporate orders?",
      answer: "Yes, we support event merch, company drops, and large quantity orders with special fulfillment pricing."
    }
  ],
  "Technical & Comparison": [
    {
      question: "How is TOBE different from marketplaces like Amazon or Flipkart?",
      answer: "Traditional marketplaces show you pre-made catalogs using keyword algorithms. TOBE understands nuanced intent — turning prompts like \"streetwear hoodie with cyberpunk graffiti\" into real, purchasable products in seconds."
    },
    {
      question: "How does TOBE's sustainability compare to fast fashion?",
      answer: "Traditional retail overproduces millions of tons of unsold apparel yearly. TOBE makes products only when ordered, cutting waste by up to 40% and dramatically lowering carbon emissions."
    },
    {
      question: "Do I need to know design or AI tools to use TOBE?",
      answer: "No — TOBE is designed for everyone. If you can describe it, you can create it."
    },
    {
      question: "Can businesses integrate TOBE into their brand workflows?",
      answer: "Yes. APIs and B2B dashboards (coming soon) will allow brands to automate custom merch generation and fulfillment directly from their websites."
    },
    {
      question: "What resolution and format are your visuals?",
      answer: "All visuals are delivered in 300 DPI, print-ready formats optimized for production, digital previews, and marketing."
    }
  ]
};

export const FAQSection = () => {
  const { ref, isVisible } = useScrollAnimation({ threshold: 0.2 });
  const [activeTab, setActiveTab] = useState("General & Capability");

  const categories = Object.keys(faqData);

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className="py-24 px-4 space-gradient space-particles relative overflow-hidden">
      <div className="max-w-6xl mx-auto relative z-10">
        <div className={`text-center mb-12 transition-all duration-700 ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
          <h2 className="text-4xl md:text-5xl font-poppins font-bold gradient-text mb-6">
            Frequently Asked Questions
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Everything you need to know about TOBE
          </p>
        </div>

        <Tabs defaultValue="General & Capability" className="w-full" onValueChange={setActiveTab}>
          <TabsList className="w-full flex md:flex-wrap justify-start md:justify-center gap-2 md:gap-4 mb-12 bg-transparent border-none p-0 h-auto overflow-x-auto md:overflow-visible pb-2 md:pb-0 scrollbar-hide">
            {categories.map((category) => (
              <TabsTrigger
                key={category}
                value={category}
                className={`
                  px-4 py-2 md:px-6 md:py-3 text-sm md:text-base font-medium transition-all duration-300
                  rounded-lg relative bg-transparent border-none shadow-none flex-shrink-0
                  data-[state=active]:bg-transparent data-[state=active]:text-primary
                  data-[state=inactive]:text-muted-foreground hover:text-foreground hover:bg-transparent
                  data-[state=active]:shadow-none
                `}
              >
                <span className="relative z-10 whitespace-nowrap">{category}</span>
                <span
                  className={`
                    absolute bottom-0 left-0 right-0 h-0.5 bg-gradient-to-r from-primary to-secondary rounded-full
                    transition-all duration-300 ease-in-out
                    ${activeTab === category ? 'opacity-100 scale-x-100' : 'opacity-0 scale-x-0'}
                  `}
                />
              </TabsTrigger>
            ))}
          </TabsList>

          {categories.map((category) => (
            <TabsContent
              key={category}
              value={category}
              className="mt-0 data-[state=active]:animate-in data-[state=active]:fade-in-0 data-[state=active]:slide-in-from-bottom-4 data-[state=active]:duration-500"
            >
              <Accordion type="single" collapsible className="w-full space-y-4">
                {faqData[category as keyof typeof faqData].map((item, index) => (
                  <AccordionItem
                    key={index}
                    value={`item-${index}`}
                    className="card-gradient rounded-2xl border border-border/50 px-6 py-2 hover:border-primary/30 transition-all duration-300 hover:shadow-lg"
                  >
                    <AccordionTrigger className="text-left font-semibold text-foreground hover:no-underline py-4 transition-colors duration-200">
                      {item.question}
                    </AccordionTrigger>
                    <AccordionContent className="text-muted-foreground leading-relaxed pb-4 text-base">
                      {item.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </TabsContent>
          ))}
        </Tabs>
      </div>
    </section>
  );
};

